services:
  liveaction-otel-collector:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - ./otel-collector-config-liveaction.yml:/etc/otel/config.yaml
      - ./customerlogs/:/customerlogs/

